name: RuboCop Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rubocop:
    name: RuboCop
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle || true
          bundle install --jobs 4 --retry 3

      - name: Run RuboCop
        # Use the GitHub formatter so offenses appear as annotations in PRs
        run: bundle exec rubocop --format github
